# Generated by Django 5.0 on 2023-12-27 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='dishes_cate_name_65e6c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name_en', models.CharField(max_length=200)),
                ('name_kg', models.CharField(default='Тамак', max_length=200)),
                ('name_ru', models.CharField(default='Еда', max_length=200)),
                ('description_en', models.TextField()),
                ('description_kg', models.TextField(default='Тамак')),
                ('description_ru', models.TextField(default='Еда')),
                ('price', models.FloatField()),
                ('gram', models.CharField(default='200', max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(default='food1.png', upload_to='dishes/')),
                ('is_trend', models.IntegerField(choices=[(0, 'Trend'), (1, 'Not trend')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='dishes.category')),
            ],
            options={
                'db_table': 'dish',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name_en', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
                ('name_kg', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additives', to='dishes.dish')),
            ],
            options={
                'db_table': 'additive',
            },
        ),
    ]
