# Generated by Django 5.0 on 2023-12-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['created'], 'verbose_name_plural': 'dishes'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='available',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Unavailable')], default=0),
        ),
    ]
